<?php


namespace app\admin\controller;


use think\Controller;

class Login extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        return $this->fetch();
    }
}