<?php


namespace app\index\controller;



use CasbinAdapter\Think\Facades\Casbin;
use think\Controller;

class Test extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
//        Casbin::addPolicy('alice', 'data1', 'read2');
//        //$res=new Enforcer();
//        Casbin::addRoleForUser('alice', 'admin');
//        dump(Casbin::hasPolicy('alice', 'data1', 'read1'));

        Casbin::addRoleForUser('alice', 'admin');
        // bob has the member role
        Casbin::addRoleForUser('bob', 'member');

        Casbin::addPermissionForUser('member', '/foo', 'GET');
        Casbin::addPermissionForUser('member', '/foo/:id', 'GET');
        // admin inherits all permissions of member
        Casbin::addRoleForUser('admin', 'member');
        Casbin::addPermissionForUser('admin', '/foo', 'POST');
        Casbin::addPermissionForUser('admin', '/foo/:id', 'PUT');
        Casbin::addPermissionForUser('admin', '/foo/:id', 'DELETE');
        //删除
        //deletePermissionForUser

        //移除
        //Casbin::removePolicy('alice', 'data1', 'read');
//验证

//        $enforcer->enforce('alice', '/foo', 'GET'); // true
//        $enforcer->enforce('alice', '/foo', 'GET'); // true
//
//        $enforcer->enforce('alice', '/foo', 'POST'); // true
//        $enforcer->enforce('alice', '/foo/1', 'PUT'); // true
//        $enforcer->enforce('alice', '/foo/1', 'DELETE');

        echo "111";
    }

}